// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.installation.timestamp", "133803812917983176");
user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "b46c2668-c7fa-460b-a41d-25bce1b87afc");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.background.allowUpdatesForUnelevatedInstallations", true);
user_pref("app.update.background.lastInstalledTaskVersion", 4);
user_pref("app.update.background.rolledout", true);
user_pref("app.update.download.attempts", 0);
user_pref("app.update.elevate.attempts", 0);
user_pref(
  "app.update.lastUpdateTime.addon-background-update-timer",
  1736844989
);
user_pref("app.update.lastUpdateTime.background-update-timer", 1736859389);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1736859509);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1736852386);
user_pref("app.update.lastUpdateTime.region-update-timer", 1736774904);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1736857854);
user_pref(
  "app.update.lastUpdateTime.services-settings-poll-changes",
  1736844989
);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1736775024);
user_pref(
  "app.update.lastUpdateTime.telemetry_untrustedmodules_ping",
  1736844989
);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1736844989);
user_pref("app.update.migrated.updateDir3.93E67FFACB149F95", true);
user_pref("browser.aboutConfig.showWarning", false);
user_pref("browser.bookmarks.showMobileBookmarks", false);
user_pref("browser.compactmode.show", true);
user_pref("browser.contentblocking.category", "standard");
user_pref(
  "browser.contextual-services.contextId",
  "{5aa3c4c4-ab64-44c3-b552-aa0443df995d}"
);
user_pref("browser.crashReports.unsubmittedCheck.autoSubmit2", true);
user_pref("browser.crashReports.unsubmittedCheck.lastShownDate", "20250113");
user_pref("browser.ctrlTab.sortByRecentlyUsed", true);
user_pref("browser.disableResetPrompt", true);
user_pref(
  "browser.download.lastDir",
  "C:\\Users\\otto.jonas\\OneDrive - J.C. Peacock & Co. LTD\\Desktop"
);
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.eme.ui.firstContentShown", true);
user_pref("browser.engagement.ctrlTab.has-used", true);
user_pref("browser.engagement.downloads-button.has-used", true);
user_pref("browser.engagement.sidebar-button.has-used", true);
user_pref("browser.firefox-view.view-count", 2);
user_pref("browser.laterrun.bookkeeping.updateAppliedTime", 1736243393);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migrate.interactions.bookmarks", true);
user_pref("browser.migrate.interactions.history", true);
user_pref("browser.migrate.interactions.passwords", true);
user_pref("browser.migration.version", 150);
user_pref("browser.ml.chat.enabled", true);
user_pref("browser.ml.chat.provider", "https://chatgpt.com");
user_pref(
  "browser.newtabpage.activity-stream.discoverystream.spoc.impressions",
  '{"CAISBWV0b3Jv":[1736173179612]}'
);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref(
  "browser.newtabpage.activity-stream.impressionId",
  "{b8cfbc1e-4578-4fc1-8471-1b3d61d85c72}"
);
user_pref(
  "browser.newtabpage.activity-stream.section.highlights.includeDownloads",
  false
);
user_pref(
  "browser.newtabpage.activity-stream.section.highlights.includePocket",
  false
);
user_pref(
  "browser.newtabpage.activity-stream.section.highlights.includeVisited",
  false
);
user_pref("browser.newtabpage.activity-stream.section.highlights.rows", 4);
user_pref("browser.newtabpage.activity-stream.showSponsored", false);
user_pref("browser.newtabpage.activity-stream.showSponsoredTopSites", false);
user_pref("browser.newtabpage.activity-stream.topSitesRows", 2);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref(
  "browser.pageActions.persistedActions",
  '{"ids":["bookmark"],"idsInUrlbar":["bookmark"],"idsInUrlbarPreProton":[],"version":1}'
);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.privacySegmentation.createdShortcut", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1736774904);
user_pref("browser.rights.3.shown", true);
user_pref(
  "browser.safebrowsing.provider.google4.lastupdatetime",
  "1736860888872"
);
user_pref(
  "browser.safebrowsing.provider.google4.nextupdatetime",
  "1736862674872"
);
user_pref(
  "browser.safebrowsing.provider.mozilla.lastupdatetime",
  "1736844993907"
);
user_pref(
  "browser.safebrowsing.provider.mozilla.nextupdatetime",
  "1736866593907"
);
user_pref("browser.search.region", "GB");
user_pref(
  "browser.search.serpEventTelemetryCategorization.regionEnabled",
  false
);
user_pref("browser.search.totalSearches", 63);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20250113214519");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1736857853");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20250113214519");
user_pref("browser.startup.homepage_override.mstone", "136.0a1");
user_pref("browser.startup.lastColdStartupCheck", 1736857851);
user_pref("browser.startup.page", 3);
user_pref(
  "browser.startup.windowsLaunchOnLogin.disableLaunchOnLoginPrompt",
  true
);
user_pref("browser.tabs.loadInBackground", false);
user_pref("browser.tabs.warnOnClose", true);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.toolbarbuttons.introduced.sidebar-button", true);
user_pref("browser.toolbars.bookmarks.visibility", "never");
user_pref(
  "browser.uiCustomization.horizontalTabsBackup",
  '{"placements":{"widget-overflow-fixed-list":[],"unified-extensions-area":["gitkraken-browser_gitkraken_com-browser-action","firefoxcolor_mozilla_com-browser-action","_react-devtools-browser-action","_bbb880ce-43c9-47ae-b746-c3e0096c5b76_-browser-action","treestyletab_piro_sakura_ne_jp-browser-action"],"nav-bar":["sidebar-button","back-button","forward-button","stop-reload-button","customizableui-special-spring1","vertical-spacer","urlbar-container","customizableui-special-spring2","save-to-pocket-button","downloads-button","fxa-toolbar-menu-button","reset-pbm-toolbar-button","unified-extensions-button"],"toolbar-menubar":["menubar-items"],"TabsToolbar":["firefox-view-button","tabbrowser-tabs","new-tab-button","alltabs-button"],"vertical-tabs":[],"PersonalToolbar":["personal-bookmarks"]},"seen":["save-to-pocket-button","reset-pbm-toolbar-button","profiler-button","developer-button","gitkraken-browser_gitkraken_com-browser-action","firefoxcolor_mozilla_com-browser-action","_react-devtools-browser-action","_bbb880ce-43c9-47ae-b746-c3e0096c5b76_-browser-action","treestyletab_piro_sakura_ne_jp-browser-action"],"dirtyAreaCache":["nav-bar","vertical-tabs","unified-extensions-area"],"currentVersion":21,"newElementCount":2}'
);
user_pref(
  "browser.uiCustomization.horizontalTabstrip",
  '["tabbrowser-tabs","new-tab-button"]'
);
user_pref(
  "browser.uiCustomization.state",
  '{"placements":{"widget-overflow-fixed-list":[],"unified-extensions-area":["gitkraken-browser_gitkraken_com-browser-action","firefoxcolor_mozilla_com-browser-action","_react-devtools-browser-action","_bbb880ce-43c9-47ae-b746-c3e0096c5b76_-browser-action","treestyletab_piro_sakura_ne_jp-browser-action","addons_wakatime_com-browser-action"],"nav-bar":["sidebar-button","back-button","forward-button","stop-reload-button","customizableui-special-spring1","vertical-spacer","urlbar-container","customizableui-special-spring2","downloads-button","reset-pbm-toolbar-button","unified-extensions-button"],"toolbar-menubar":["menubar-items"],"TabsToolbar":[],"vertical-tabs":["tabbrowser-tabs"],"PersonalToolbar":["personal-bookmarks"]},"seen":["save-to-pocket-button","reset-pbm-toolbar-button","profiler-button","developer-button","gitkraken-browser_gitkraken_com-browser-action","firefoxcolor_mozilla_com-browser-action","_react-devtools-browser-action","_bbb880ce-43c9-47ae-b746-c3e0096c5b76_-browser-action","treestyletab_piro_sakura_ne_jp-browser-action","addons_wakatime_com-browser-action"],"dirtyAreaCache":["nav-bar","vertical-tabs","unified-extensions-area","TabsToolbar","toolbar-menubar","PersonalToolbar"],"currentVersion":21,"newElementCount":2}'
);
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.placeholderName.private", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("browser.urlbar.showSearchTerms.enabled", false);
user_pref("browser.urlbar.suggest.searches", false);
user_pref("captchadetection.hasUnsubmittedData", false);
user_pref("captchadetection.lastSubmission", 1736852);
user_pref(
  "datareporting.dau.cachedUsageProfileID",
  "148ac137-169d-47df-8b33-147c473c84f9"
);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref(
  "datareporting.policy.dataSubmissionPolicyNotifiedTime",
  "1736170086662"
);
user_pref("devtools.debugger.features.windowless-service-workers", true);
user_pref("devtools.debugger.prefs-schema-version", 11);
user_pref("devtools.everOpened", true);
user_pref("devtools.netmonitor.msg.visibleColumns", '["data","time"]');
user_pref("devtools.performance.popup.intro-displayed", true);
user_pref("devtools.toolbox.host", "left");
user_pref("devtools.toolbox.previousHost", "bottom");
user_pref("devtools.toolbox.selectedTool", "webconsole");
user_pref("devtools.toolbox.sidebar.width", 643);
user_pref("devtools.toolbox.splitconsole.open", true);
user_pref("devtools.toolsidebar-height.inspector", 350);
user_pref("devtools.toolsidebar-width.inspector", 700);
user_pref("devtools.toolsidebar-width.inspector.splitsidebar", 250);
user_pref("devtools.webextensions.@react-devtools.enabled", true);
user_pref("devtools.webextensions.addons@wakatime.com.enabled", true);
user_pref(
  "devtools.webextensions.{e748cb59-4901-4bea-b74a-1d8dab98e3c7}.enabled",
  true
);
user_pref("distribution.iniFile.exists.appversion", "136.0a1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "GB");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "479cecddc1b24194a07aab6a2cda3649");
user_pref("dom.security.https_only_mode_ever_enabled", true);
user_pref("extensions.activeThemeID", "{87adc190-0881-4325-8f33-166782c657e0}");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.cache.lastUpdate", 1736518295);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20250113214519");
user_pref("extensions.lastAppVersion", "136.0a1");
user_pref("extensions.lastPlatformVersion", "136.0a1");
user_pref("extensions.pendingOperations", false);
user_pref(
  "extensions.pictureinpicture.enable_picture_in_picture_overrides",
  true
);
user_pref("extensions.quarantineIgnoredByUser.addons@wakatime.com", true);
user_pref(
  "extensions.quarantinedDomains.list",
  "autoatendimento.bb.com.br,ibpf.sicredi.com.br,ibpj.sicredi.com.br,internetbanking.caixa.gov.br,www.ib12.bradesco.com.br,www2.bancobrasil.com.br"
);
user_pref("extensions.systemAddonSet", '{"schema":1,"addons":{}}');
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.extension.hidden", false);
user_pref("extensions.ui.lastCategory", "addons://list/theme");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.ui.sitepermission.hidden", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref(
  "extensions.webextensions.ExtensionStorageIDB.migrated.@react-devtools",
  true
);
user_pref(
  "extensions.webextensions.ExtensionStorageIDB.migrated.FirefoxColor@mozilla.com",
  true
);
user_pref(
  "extensions.webextensions.ExtensionStorageIDB.migrated.gitkraken-browser@gitkraken.com",
  true
);
user_pref(
  "extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org",
  true
);
user_pref(
  "extensions.webextensions.ExtensionStorageIDB.migrated.treestyletab@piro.sakura.ne.jp",
  true
);
user_pref(
  "extensions.webextensions.ExtensionStorageIDB.migrated.{bbb880ce-43c9-47ae-b746-c3e0096c5b76}",
  true
);
user_pref(
  "extensions.webextensions.uuids",
  '{"formautofill@mozilla.org":"195862c4-d299-41b0-8bd7-e93e03d0be25","pictureinpicture@mozilla.org":"06b3e5c5-5f55-4962-8155-5cd8667e41eb","screenshots@mozilla.org":"ed50e0bb-56f3-41cf-be15-0d203ea98082","webcompat-reporter@mozilla.org":"ca341384-f5b2-4136-8b1e-afba58650c5c","webcompat@mozilla.org":"e63de873-369c-4f98-9d43-b5d7dd0ef0f5","default-theme@mozilla.org":"e639de60-6b7f-4fd3-89e0-af4716d95e5f","addons-search-detection@mozilla.com":"aa02ebbd-ddb8-4f81-bd21-467b1ee38abf","gitkraken-browser@gitkraken.com":"97d64f66-23f3-4898-8dff-13526cd48d0e","tranquility@ushnisha.com":"fa14ca9e-3eb3-4027-9845-04f11b0a1f11","FirefoxColor@mozilla.com":"218b358d-3bf8-4a29-8a61-b0d0d906de2f","treestyletab@piro.sakura.ne.jp":"9ee46754-d8d3-4e0a-ad2a-b4103ad2d604","@react-devtools":"e66f400d-436d-4e78-b119-edd936cdce41","{bbb880ce-43c9-47ae-b746-c3e0096c5b76}":"e14ce993-d8c4-4e0a-9013-f59e458e9302","{e748cb59-4901-4bea-b74a-1d8dab98e3c7}":"d0644c84-6ec7-486f-9f6e-c5deff1f8394","{3ed642ce-554e-4329-ae49-12ee7717d491}":"c7058547-48ca-4b57-8d90-efb13438030e","{87adc190-0881-4325-8f33-166782c657e0}":"4d80fae6-8f37-4268-b57a-3caaf15d4b50","addons@wakatime.com":"b1cf6748-7ff3-4e29-a4c9-42a4a425f80d"}'
);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx-shader-check.build-version", "20250113214519");
user_pref("gfx-shader-check.device-id", "0x7d45");
user_pref("gfx-shader-check.driver-version", "32.0.101.5542");
user_pref("gfx-shader-check.ptr-size", 8);
user_pref(
  "identity.fxaccounts.account.device.name",
  "otto.jonas’s Nightly on JCP-003336"
);
user_pref(
  "identity.fxaccounts.account.telemetry.sanitized_uid",
  "b2fc6f764f166138fdb0499f79b216fa"
);
user_pref("identity.fxaccounts.commands.missed.last_fetch", 1736852984);
user_pref("identity.fxaccounts.toolbar.accessed", true);
user_pref("idle.lastDailyNotification", 1736844988);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-msvc-x64");
user_pref(
  "media.gmp-gmpopenh264.hashValue",
  "b667086ed49579592d435df2b486fe30ba1b62ddd169f19e700cd079239747dd3e20058c285fa9c10a533e34f22b5198ed9b1f92ae560a3067f3e3feacc724f1"
);
user_pref("media.gmp-gmpopenh264.lastDownload", 1736170116);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1736170116);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1736170117);
user_pref("media.gmp-gmpopenh264.version", "2.3.2");
user_pref("media.gmp-manager.buildID", "20250113214519");
user_pref("media.gmp-manager.lastCheck", 1736855074);
user_pref("media.gmp-manager.lastEmptyCheck", 1736855074);
user_pref("media.gmp-widevinecdm.abi", "x86_64-msvc-x64");
user_pref(
  "media.gmp-widevinecdm.hashValue",
  "03105dcf804e4713b6ed7c281ad0343ac6d6eb2aed57a897c6a09515a8c7f3e06b344563e224365dc9159cfd8ed3ef665d6aec18cc07aaad66eed0dc4957dde3"
);
user_pref("media.gmp-widevinecdm.lastDownload", 1736170118);
user_pref("media.gmp-widevinecdm.lastInstallStart", 1736170116);
user_pref("media.gmp-widevinecdm.lastUpdate", 1736170119);
user_pref("media.gmp-widevinecdm.version", "4.10.2830.0");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref(
  "media.videocontrols.picture-in-picture.video-toggle.first-seen-secs",
  1736413681
);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 1);
user_pref("network.http.windows-sso.enabled", true);
user_pref(
  "nimbus.syncdefaultsstore.upgradeDialog",
  '{"slug":"upgrade-spotlight-rollout","branch":{"slug":"treatment","ratio":1,"feature":{"value":null,"enabled":true,"featureId":"upgradeDialog"},"features":null},"active":true,"experimentType":"rollout","source":"rs-loader","userFacingName":"Upgrade Spotlight Rollout","userFacingDescription":"Experimenting on onboarding content when you upgrade Firefox.","lastSeen":"2025-01-06T13:28:07.436Z","featureIds":["upgradeDialog"],"prefs":[],"isRollout":true}'
);
user_pref("nimbus.syncdefaultsstore.upgradeDialog.enabled", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1736844990);
user_pref(
  "privacy.bounceTrackingProtection.hasMigratedUserActivationData",
  true
);
user_pref("privacy.clearOnShutdown_v2.formData", true);
user_pref("privacy.history.custom", true);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.purge_trackers.last_purge", "1736844991193");
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3", true);
user_pref(
  "privacy.sanitize.pending",
  '[{"id":"newtab-container","itemsToClear":[],"options":{}}]'
);
user_pref("privacy.userContext.extension", "treestyletab@piro.sakura.ne.jp");
user_pref("sanity-test.device-id", "0x7d45");
user_pref("sanity-test.driver-version", "32.0.101.5542");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20250113214519");
user_pref("security.webauthn.show_ms_settings_link", true);
user_pref(
  "services.settings.blocklists.addons-bloomfilters.last_check",
  1736852231
);
user_pref("services.settings.blocklists.gfx.last_check", 1736852231);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", '"1736851817046"');
user_pref("services.settings.last_update_seconds", 1736852231);
user_pref(
  "services.settings.main.addons-manager-settings.last_check",
  1736852231
);
user_pref(
  "services.settings.main.anti-tracking-url-decoration.last_check",
  1736852231
);
user_pref(
  "services.settings.main.bounce-tracking-protection-exceptions.last_check",
  1736852231
);
user_pref("services.settings.main.cfr.last_check", 1736852231);
user_pref(
  "services.settings.main.cookie-banner-rules-list.last_check",
  1736852231
);
user_pref(
  "services.settings.main.devtools-compatibility-browsers.last_check",
  1736852231
);
user_pref("services.settings.main.devtools-devices.last_check", 1736852231);
user_pref("services.settings.main.doh-config.last_check", 1736852231);
user_pref("services.settings.main.doh-providers.last_check", 1736852231);
user_pref(
  "services.settings.main.fingerprinting-protection-overrides.last_check",
  1736852231
);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1736852231);
user_pref("services.settings.main.fxrelay-allowlist.last_check", 1736852231);
user_pref("services.settings.main.hijack-blocklists.last_check", 1736852231);
user_pref(
  "services.settings.main.language-dictionaries.last_check",
  1736852231
);
user_pref("services.settings.main.message-groups.last_check", 1736852231);
user_pref("services.settings.main.ml-inference-options.last_check", 1736852231);
user_pref(
  "services.settings.main.ml-model-allow-deny-list.last_check",
  1736852231
);
user_pref("services.settings.main.ml-onnx-runtime.last_check", 1736852231);
user_pref("services.settings.main.newtab-wallpapers-v2.last_check", 1736852231);
user_pref(
  "services.settings.main.nimbus-desktop-experiments.last_check",
  1736852231
);
user_pref(
  "services.settings.main.nimbus-secure-experiments.last_check",
  1736852231
);
user_pref(
  "services.settings.main.normandy-recipes-capabilities.last_check",
  1736852231
);
user_pref(
  "services.settings.main.partitioning-exempt-urls.last_check",
  1736852231
);
user_pref("services.settings.main.password-recipes.last_check", 1736852231);
user_pref("services.settings.main.password-rules.last_check", 1736852231);
user_pref("services.settings.main.public-suffix-list.last_check", 1736852231);
user_pref("services.settings.main.query-stripping.last_check", 1736852231);
user_pref("services.settings.main.remote-permissions.last_check", 1736852231);
user_pref(
  "services.settings.main.search-categorization.last_check",
  1736852231
);
user_pref("services.settings.main.search-config-icons.last_check", 1736852231);
user_pref(
  "services.settings.main.search-config-overrides-v2.last_check",
  1736852231
);
user_pref("services.settings.main.search-config-v2.last_check", 1736852231);
user_pref(
  "services.settings.main.search-default-override-allowlist.last_check",
  1736852231
);
user_pref("services.settings.main.search-telemetry-v2.last_check", 1736852231);
user_pref("services.settings.main.sites-classification.last_check", 1736852231);
user_pref(
  "services.settings.main.third-party-cookie-blocking-exempt-urls.last_check",
  1736852231
);
user_pref("services.settings.main.tippytop.last_check", 1736852231);
user_pref("services.settings.main.top-sites.last_check", 1736852231);
user_pref(
  "services.settings.main.tracking-protection-lists.last_check",
  1736852231
);
user_pref("services.settings.main.translations-models.last_check", 1736852231);
user_pref("services.settings.main.translations-wasm.last_check", 1736852231);
user_pref(
  "services.settings.main.url-classifier-skip-urls.last_check",
  1736852231
);
user_pref(
  "services.settings.main.url-parser-default-unknown-schemes-interventions.last_check",
  1736852231
);
user_pref(
  "services.settings.main.urlbar-persisted-search-terms.last_check",
  1736852231
);
user_pref(
  "services.settings.main.websites-with-shared-credential-backends.last_check",
  1736852231
);
user_pref(
  "services.settings.security-state.cert-revocations.last_check",
  1736852231
);
user_pref(
  "services.settings.security-state.intermediates.last_check",
  1736852231
);
user_pref("services.settings.security-state.onecrl.last_check", 1736852231);
user_pref("services.sync.addons.lastSync", "1736554948.53");
user_pref("services.sync.addons.syncID", "nZIrvYAroVx0");
user_pref("services.sync.addresses.lastSync", "0");
user_pref("services.sync.addresses.syncID", "wpupkMukB7Jy");
user_pref("services.sync.client.GUID", "Anf58iKHcE4C");
user_pref("services.sync.client.syncID", "ld7ujVdWL5zv");
user_pref("services.sync.clients.devices.desktop", 5);
user_pref("services.sync.clients.devices.mobile", 1);
user_pref("services.sync.clients.lastRecordUpload", 1736857858);
user_pref("services.sync.clients.lastSync", "1736857858.82");
user_pref("services.sync.clients.syncID", "K6tm6ngwLIS1");
user_pref("services.sync.creditcards.lastSync", "1736170122.31");
user_pref("services.sync.creditcards.syncID", "7tYEdAWHXEdk");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.engine.addresses", true);
user_pref("services.sync.engine.bookmarks.validation.lastTime", 1736852985);
user_pref("services.sync.engine.creditcards", true);
user_pref("services.sync.engine.passwords.validation.lastTime", 1736852985);
user_pref("services.sync.engine.prefs.modified", false);
user_pref("services.sync.forms.lastSync", "1736853588.14");
user_pref("services.sync.forms.syncID", "62k8uCE1eLEy");
user_pref("services.sync.globalScore", 29);
user_pref("services.sync.lastPing", 1736845594);
user_pref(
  "services.sync.lastSync",
  "Tue Jan 14 2025 13:32:05 GMT+0000 (Greenwich Mean Time)"
);
user_pref("services.sync.lastTabFetch", 1736861524);
user_pref("services.sync.nextSync", 1736862125);
user_pref("services.sync.prefs.lastSync", "1736767593.72");
user_pref(
  "services.sync.prefs.sync-seen.browser.contentblocking.category",
  true
);
user_pref(
  "services.sync.prefs.sync-seen.browser.crashReports.unsubmittedCheck.autoSubmit2",
  true
);
user_pref(
  "services.sync.prefs.sync-seen.browser.ctrlTab.sortByRecentlyUsed",
  true
);
user_pref(
  "services.sync.prefs.sync-seen.browser.newtabpage.activity-stream.feeds.section.highlights",
  true
);
user_pref(
  "services.sync.prefs.sync-seen.browser.newtabpage.activity-stream.feeds.section.topstories",
  true
);
user_pref(
  "services.sync.prefs.sync-seen.browser.newtabpage.activity-stream.feeds.topsites",
  true
);
user_pref(
  "services.sync.prefs.sync-seen.browser.newtabpage.activity-stream.section.highlights.includeBookmarks",
  true
);
user_pref(
  "services.sync.prefs.sync-seen.browser.newtabpage.activity-stream.section.highlights.includeDownloads",
  true
);
user_pref(
  "services.sync.prefs.sync-seen.browser.newtabpage.activity-stream.section.highlights.includePocket",
  true
);
user_pref(
  "services.sync.prefs.sync-seen.browser.newtabpage.activity-stream.section.highlights.includeVisited",
  true
);
user_pref(
  "services.sync.prefs.sync-seen.browser.newtabpage.activity-stream.section.highlights.rows",
  true
);
user_pref(
  "services.sync.prefs.sync-seen.browser.newtabpage.activity-stream.showSearch",
  true
);
user_pref(
  "services.sync.prefs.sync-seen.browser.newtabpage.activity-stream.showSponsored",
  true
);
user_pref(
  "services.sync.prefs.sync-seen.browser.newtabpage.activity-stream.showSponsoredTopSites",
  true
);
user_pref(
  "services.sync.prefs.sync-seen.browser.newtabpage.activity-stream.topSitesRows",
  true
);
user_pref("services.sync.prefs.sync-seen.browser.newtabpage.enabled", true);
user_pref("services.sync.prefs.sync-seen.browser.startup.homepage", true);
user_pref("services.sync.prefs.sync-seen.browser.startup.page", true);
user_pref("services.sync.prefs.sync-seen.browser.tabs.loadInBackground", true);
user_pref("services.sync.prefs.sync-seen.browser.tabs.warnOnClose", true);
user_pref(
  "services.sync.prefs.sync-seen.browser.urlbar.suggest.searches",
  true
);
user_pref(
  "services.sync.prefs.sync-seen.dom.security.https_only_mode_ever_enabled",
  true
);
user_pref("services.sync.prefs.sync-seen.extensions.activeThemeID", true);
user_pref("services.sync.prefs.sync-seen.general.autoScroll", true);
user_pref("services.sync.prefs.sync-seen.media.eme.enabled", true);
user_pref(
  "services.sync.prefs.sync-seen.privacy.clearOnShutdown_v2.cache",
  true
);
user_pref(
  "services.sync.prefs.sync-seen.privacy.clearOnShutdown_v2.cookiesAndStorage",
  true
);
user_pref(
  "services.sync.prefs.sync-seen.privacy.sanitize.sanitizeOnShutdown",
  true
);
user_pref("services.sync.prefs.sync-seen.privacy.userContext.enabled", true);
user_pref("services.sync.prefs.syncID", "0_VBv7kkgJWB");
user_pref("services.sync.syncInterval", 600000);
user_pref("services.sync.syncThreshold", 300);
user_pref("services.sync.username", "ottobjonas@outlook.com");
user_pref(
  "sidebar.backupState",
  '{"command":"","panelWidth":200,"launcherWidth":60,"expandedLauncherWidth":330,"launcherExpanded":false,"launcherVisible":true}'
);
user_pref("sidebar.revamp", true);
user_pref("sidebar.verticalTabs", true);
user_pref("signon.firefoxRelay.showToAllBrowsers", true);
user_pref("storage.vacuum.last.content-prefs.sqlite", 1736336830);
user_pref("storage.vacuum.last.index", 2);
user_pref("storage.vacuum.last.places.sqlite", 1736180422);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("toolkit.startup.last_success", 1736857846);
user_pref(
  "toolkit.telemetry.cachedClientID",
  "e21928b7-1ac5-4848-a7de-372014d2e98f"
);
user_pref(
  "toolkit.telemetry.cachedProfileGroupID",
  "73d64df1-4cf0-4a64-a9d7-4167c76d7753"
);
user_pref("toolkit.telemetry.previousBuildID", "20250113214519");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref(
  "ui.osk.debug.keyboardDisplayReason",
  "IKPOS: Keyboard presence confirmed."
);
